services:

  server:
    build: server/
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./server:/App

  client:
    build: client/
    ports:
      - "3000:3000"
    volumes:
      - ./client:/App
      - ./client/node_modules:/App/node_modules
